import type { MDXComponents } from 'next-mdx-remote-client/rsc'
import {
  Matrix,
  Scene,
  Step,
  ArrowOverlay,
  Anchor,
  Arrow,
  TensorSlices,
  TensorExplorer,
  Tabs,
  Node,
  Group,
  Flow,
  Detail,
  DetailRail,
  DetailRailProvider,
  TensorDive,
  BracketDiagram,
} from '@strides/viz'
import { AttentionHeatmap, HeadSplitViz, TokenJourney } from '@strides/viz-ml'

/** Viz components available to every page's MDX by default, ahead of the caller's own component map. */
export const defaultComponents: MDXComponents = {
  Matrix,
  Scene,
  Step,
  ArrowOverlay,
  Anchor,
  Arrow,
  TensorSlices,
  TensorExplorer,
  Tabs,
  Node,
  Group,
  Flow,
  Detail,
  DetailRail,
  DetailRailProvider,
  TensorDive,
  BracketDiagram,
  AttentionHeatmap,
  HeadSplitViz,
  TokenJourney,
}
